### ISSUE TITLE
flutter web release & profile mode  NoSuchMethodError: method not found: '$mul' (x0.$mul is not a function)

### ISSUE THREAD

**Issue by wasabia** [wasabia/three_dart#12]
```
NoSuchMethodError: method not found: '$mul' (x0.$mul is not a function)
js_primitives.dart:47     at QuaternionLinearInterpolant.interpolate$4 (http://localhost:58879/main.dart.js:59067:30)
js_primitives.dart:47     at QuaternionLinearInterpolant.evaluate$1 (http://localhost:58879/main.dart.js:59168:20)
js_primitives.dart:47     at webgl_debugState_build_closure0.call$0 (http://localhost:58879/main.dart.js:59056:10)
js_primitives.dart:47     at _InkResponseState._handleTap$0 (http://localhost:58879/main.dart.js:66805:27)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:58879/main.dart.js:7354:45)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$1$3$debugReport (http://localhost:58879/main.dart.js:63892:27)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$2 (http://localhost:58879/main.dart.js:63902:19)
js_primitives.dart:47     at TapGestureRecognizer.handleTapUp$2$down$up (http://localhost:58879/main.dart.js:64221:18)
js_primitives.dart:47     at TapGestureRecognizer._checkUp$0 (http://localhost:58879/main.dart.js:64163:13)
js_primitives.dart:47     at TapGestureRecognizer.handlePrimaryPointer$1 (http://localhost:58879/main.dart.js:64092:15)
```

**Comment by mark-apn** [comment]
Closing because its stale and most likely fixed by the referenced flutter issue
