### ISSUE TITLE
Multiple issues with library example on windows

### ISSUE THREAD

**Issue by giiyms** [wasabia/three_dart#122]
webgl_camera_array:

```text
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'String'
#0      quadraticBezier
interpolations.dart:31
#1      QuadraticBezierCurve.getPoint
quadratic_bezier_curve.dart:31
#2      Curve.getLengths
curve.dart:145
#3      Curve.getUtoTmapping
curve.dart:170
#4      Curve.getTangentAt
curve.dart:256
#5      Curve.computeFrenetFrames
curve.dart:277
#6      new TubeGeometry
tube_geometry.dart:24
#7      _MyAppState.initPage
webgl_camera_array.dart:262
#8      _MyAppState.initScene
webgl_camera_array.dart:198
#9      _MyAppState.initPlatformState.<anonymous closure>
webgl_camera_array.dart:75
<asynchronous suspension>
```

Going back a page:
```txt
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel flutter_gl)
#0      MethodChannel._invokeMethod
platform_channel.dart:313
<asynchronous suspension>
#1      MethodChannelFlutterGl.dispose_interface
method_channel_flutter_gl.dart:54
<asynchronous suspension>
```

webgl_geometry_text is a black screen

webgl_geometry_shapes

```txt
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'double' is not a subtype of type 'String'
#0      quadraticBezier
interpolations.dart:31
#1      QuadraticBezierCurve.getPoint
quadratic_bezier_curve.dart:31
#2      Curve.getPoints
curve.dart:108
#3      CurvePath.getPoints
curve_path.dart:156
#4      Shape.extractPoints
shape.dart:39
#5      ShapeGeometry.init.addShape
shape_geometry.dart:60
#6      ShapeGeometry.init
shape_geometry.dart:114
#7      new ShapeGeometry
shape_geometry.dart:16
#8      _MyAppState.addShape
webgl_geometry_shapes.dart:392
#9      _MyAppState.initPage
webgl_geometry_shapes.dart:367
<asynchronous suspension>
```

webgl_loader_gltf:

```txt
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'GLTFParser' has no instance getter '_markDefs'.
Receiver: Instance of 'GLTFParser'
Tried calling: _markDefs
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      GLTFParser.parse.<anonymous closure>
gltf_parser.dart:96
#2      GLTFParser._invokeAll
gltf_parser.dart:203
#3      GLTFParser.parse
gltf_parser.dart:95
#4      GLTFLoader.parse
gltf_loader.dart:276
#5      GLTFLoader.load.<anonymous closure>
gltf_loader.dart:115
#6      FileLoader.load
file_loader.dart:202
<asynchronous suspension>
5
flutter: loader: Instance of 'TextureLoader'
flutter:  set values roughness: 1.0
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '<=' was called on null.
Receiver: null
Tried calling: <=(1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      GLTFParser._getNodeRef
gltf_parser.dart:177
#2      GLTFParser.createNodeMesh
gltf_parser.dart:1275
<asynchronous suspension>
#3      GLTFParser._invokeOne
gltf_parser.dart:191
<asynchronous suspension>
#4      GLTFParser.loadNode
gltf_parser.dart:1306
<asynchronous suspension>
#5      GLTFParser.getDependency
gltf_parser.dart:228
<asynchronous suspension>
#6      GLTFParser.buildNodeHierarchy
gltf_parser.dart:1412
<asynchronous suspension>
#7      GLTFParser.loadScene
gltf_parser.dart:1490
<asynchronous suspension>
#8      GLTFParser.getDependency
gltf_parser.dart:224
<asynchronous suspension>
#9      GLTFParser.getDependencies
gltf_parser.dart:304
<asynchronous suspension>
#10     GLTFParser.parse
gltf_parser.dart:99
<asynchronous suspension>
```

**Comment by HenriqueCrj** [comment]
Same problem here
