### ISSUE TITLE
Error: RangeError (index): Index out of range: index should be less than 2: 2

### ISSUE THREAD

**Issue by mkasaii16** [wasabia/three_dart#59]
when run obj file in flutter web

Error: RangeError (index): Index out of range: index should be less than 2: 2
    at Object.throw_ [as throw] (http://localhost:64405/dart_sdk.js:5080:11)
    at [dartx._get] (http://localhost:64405/dart_sdk.js:17547:21)
at index$6.OBJLoader.new.parse (http://localhost:64405/packages/three_dart_jsm/three_dart_jsm/loaders/index.dart.lib.js:993:122)
    at parse.next (<anonymous>)
    at runBody (http://localhost:64405/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:64405/dart_sdk.js:40691:7)
at index$6.OBJLoader.new.parse (http://localhost:64405/packages/three_dart_jsm/three_dart_jsm/loaders/index.dart.lib.js:934:20)
at http://localhost:64405/packages/three_dart_jsm/three_dart_jsm/loaders/index.dart.lib.js:926:42
    at Generator.next (<anonymous>)
    at runBody (http://localhost:64405/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:64405/dart_sdk.js:40691:7)
at http://localhost:64405/packages/three_dart_jsm/three_dart_jsm/loaders/index.dart.lib.js:925:46
    at Object._checkAndCall (http://localhost:64405/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:64405/dart_sdk.js:5284:17)
at index.FileLoader.new.load (http://localhost:64405/packages/three_dart/three3d/ThreeHelper.dart.lib.js:2597:70)
    at load.next (<anonymous>)
    at http://localhost:64405/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:64405/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:64405/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:64405/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:64405/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:64405/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64405/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:64405/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:64405/dart_sdk.js:40784:13)
    at http://localhost:64405/dart_sdk.js:36261:9

**Comment by mark-apn** [comment]
Can you elaborate a bit on this issue? Maybe provide a gist or repo with a reproduce-able case?
