### ISSUE TITLE
渲染自己的 GLTF 时报错

### ISSUE THREAD

**Issue by zhou67832033** [wasabia/three_dart#7]
[animate7.gltf.zip](https://github.com/wasabia/three_dart/files/7785528/animate7.gltf.zip)

我将 webgl_loader_gltf 中的模型替换为 animate7.gltf 进行渲染时，报以下错误：

Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 475ms.
Height of Platform View type: [1640708149501000] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [1640708149501000] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
 OpenGLContextWeb 
{gl: [object WebGL2RenderingContext]}
 WebGLState..................init........... 
 WebGLState. getParameter _data: [0, 0, 2400, 1504]
render cost: 5 
{geometries: 0, textures: 0}
{frame: 1, calls: 0, triangles: 0, points: 0, lines: 0}
 ----------indices-----3 
Error: type 'Null' is not a 'bool' in boolean expression
    at Object.throw_ [as throw] (http://localhost:65522/dart_sdk.js:5063:11)
    at Object.booleanConversionFailed (http://localhost:65522/dart_sdk.js:5359:15)
    at Object.dtest (http://localhost:65522/dart_sdk.js:5354:42)
    at index$7.GLTFLightsExtension.new.[_loadLight] (http://localhost:65522/packages/three_dart_jsm/three_dart_jsm/loaders/gltf/index.dart.lib.js:437:16)
    at index$7.GLTFLightsExtension.new.<anonymous> (http://localhost:65522/packages/three_dart_jsm/three_dart_jsm/loaders/gltf/index.dart.lib.js:521:36)
    at Object._checkAndCall (http://localhost:65522/dart_sdk.js:5270:16)
    at Object.callMethod (http://localhost:65522/dart_sdk.js:5313:17)
    at Object.dsend (http://localhost:65522/dart_sdk.js:5316:17)
    at http://localhost:65522/packages/three_dart_jsm/three_dart_jsm/loaders/gltf/index.dart.lib.js:2855:80
    at Generator.next (<anonymous>)
    at runBody (http://localhost:65522/dart_sdk.js:40556:34)
    at Object._async [as async] (http://localhost:65522/dart_sdk.js:40587:7)
    at http://localhost:65522/packages/three_dart_jsm/three_dart_jsm/loaders/gltf/index.dart.lib.js:2854:83
    at Object._checkAndCall (http://localhost:65522/dart_sdk.js:5270:16)
    at Object.dcall (http://localhost:65522/dart_sdk.js:5275:17)
    at index$7.GLTFParser.new._invokeAll (http://localhost:65522/packages/three_dart_jsm/three_dart_jsm/loaders/gltf/index.dart.lib.js:2164:36)
    at _invokeAll.next (<anonymous>)
    at http://localhost:65522/dart_sdk.js:40537:33
    at _RootZone.runUnary (http://localhost:65522/dart_sdk.js:40407:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:65522/dart_sdk.js:35328:29)
    at handleValueCallback (http://localhost:65522/dart_sdk.js:35896:49)
    at Function._propagateToListeners (http://localhost:65522/dart_sdk.js:35934:17)
    at _Future.new.[_completeWithValue] (http://localhost:65522/dart_sdk.js:35782:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65522/dart_sdk.js:35803:35)
    at Object._microtaskLoop (http://localhost:65522/dart_sdk.js:40675:13)
    at _startMicrotaskLoop (http://localhost:65522/dart_sdk.js:40681:13)
    at http://localhost:65522/dart_sdk.js:36156:9

**Comment by zhou67832033** [comment]
我目前在做一个 3D 相关的组件，希望能微信沟通。我的微信：jobs1990

**Comment by wasabia** [comment]
已更新，现在还不支持动画呢
