### ISSUE TITLE
load VRM model use GLTFLoader error

### ISSUE THREAD

**Issue by heyhuo** [wasabia/three_dart#81]
E/flutter (13247): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance setter 'color='.
E/flutter (13247): Receiver: _LinkedHashMap len:3
E/flutter (13247): Tried calling: color=Instance of 'Color'
E/flutter (13247): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (13247): #1      GLTFMaterialsUnlitExtension.extendParams (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFExtensions.dart:274:20)
E/flutter (13247): #2      GLTFParser.loadMaterial (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:884:29)
E/flutter (13247): #3      GLTFParser.getDependency.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:263:29)
E/flutter (13247): #4      GLTFParser.getDependency.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:261:46)
E/flutter (13247): #5      GLTFParser._invokeOne (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:195:30)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #6      GLTFParser.getDependency (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:261:24)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #7      GLTFParser.loadMesh (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1119:13)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #8      GLTFParser.getDependency.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:239:43)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #9      GLTFParser._invokeOne (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:195:20)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #10     GLTFParser.getDependency (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:238:24)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #11     GLTFParser.createNodeMesh (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1408:16)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #12     GLTFParser._invokeOne (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:195:20)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #13     GLTFParser.loadNode (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1444:23)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #14     GLTFParser.getDependency (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:234:24)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #15     GLTFParser.buildNodeHierarchy (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1556:16)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #16     GLTFParser.loadScene (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1638:7)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #17     GLTFParser.getDependency (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:230:24)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #18     GLTFParser.getDependencies (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:318:18)
E/flutter (13247): <asynchronous suspension>
E/flutter (13247): #19     GLTFParser.parse (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:95:21)
E/flutter (13247): <asynchronous suspension>

**Comment by heyhuo** [comment]
`extendParams(materialParams, materialDef, parser) async {
    List<Future> pending = [];

    materialParams['color'] = new Color(1.0, 1.0, 1.0);
    materialParams['opacity'] = 1.0;

    var metallicRoughness = materialDef['pbrMetallicRoughness'];

    if (metallicRoughness != null) {
      if (metallicRoughness['baseColorFactor'] is List) {
        var array = metallicRoughness['baseColorFactor']
            .map((e) => e.toDouble()).toList();

        materialParams['color'].fromArray(array);
        materialParams['opacity'] = array[3];
      }

      if (metallicRoughness['baseColorTexture'] != null) {
        pending.add(parser.assignTexture(
            materialParams, 'map', metallicRoughness['baseColorTexture']));
      }
    }

    return Future.wait(pending);
  }`

**Comment by heyhuo** [comment]
Function addUnknownExtensionsToUserData =
    (knownExtensions, object, Map<String, dynamic> objectDef) {
  // Add unknown glTF extensions to an object's userData.

  if (objectDef["extensions"] != null) {
    objectDef["extensions"].forEach((name, _value) {
      if (knownExtensions[name] == null) {
        object["userData"]["gltfExtensions"] =
            object["userData"]["gltfExtensions"] ?? {};
        object["userData"]["gltfExtensions"][name] =
        objectDef["extensions"][name];
      }
    });
  }
};

**Comment by wasabia** [comment]
模型文件能提供一下嘛

**Comment by heyhuo** [comment]
> 模型文件能提供一下嘛

http://i3.particlewave.cn:9001/models/vrm/black_boy.vrm

**Comment by wasabia** [comment]
three_dart_jsm 上修复了这个错误 加载出来的没有纹理
在three.js上加载这个模型 没有显示任何内容

**Comment by heyhuo** [comment]
> 

加载完模型之后应该还需要对vrm的格式转换一下才能显示纹理

**Comment by heyhuo** [comment]
> three_dart_jsm 上修复了这个错误 加载出来的没有纹理 在three.js上加载这个模型 没有显示任何内容

![3891663741021_ pic](https://user-images.githubusercontent.com/48979042/191428423-8ea673b6-d8f3-44dc-a1dc-c4e7490341c8.jpg)

**Comment by wasabia** [comment]
先试试three.js是否能正常显示，three.js的examples里没有看到这个格式 threejs也不支持？

**Comment by heyhuo** [comment]
> 先试试three.js是否能正常显示，three.js的examples里没有看到这个格式 threejs也不支持？

有VRMLoader.js，three.js里面是可以正常显示的

**Comment by heyhuo** [comment]
https://github.com/0b5vr/three-vrm-inspector
这个仓库有加载vrm的例子

**Comment by heyhuo** [comment]
我在gltfParser加载完textureCache之后，把texture重新给scene里的纹理附上之后，可以加载出模型的纹理
