### ISSUE TITLE
Object3D.clone - NoSuchMethodError: Class 'List<dynamic>' has no instance method 'clone'. 

### ISSUE THREAD

**Issue by mark-apn** [wasabia/three_dart#91]
I'm getting an error when I try to clone a Object3D from a loaded .obj

```bash 
flutter: ⚠️ 14:29:15.914601 WARNING  Logger:  - NoSuchMethodError: Class 'List<dynamic>' has no instance method 'clone'.
Receiver: Instance(length:2) of '_GrowableList'
Tried calling: clone()
flutter: ⚠️ 14:29:15.917587 WARNING  Logger:  - #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      Mesh.clone (package:three_dart/three3d/objects/Mesh.dart:41:45)
#2      Object3D.copy (package:three_dart/three3d/core/Object3D.dart:818:19)
#3      Object3D.clone (package:three_dart/three3d/core/Object3D.dart:783:23)
#4      _MapRendererState.addMarkers (package:ui/src/pages/scene/map_renderer.dart:342:33)
```

I'll try and see if I can make a PR to fix this.

**Comment by mark-apn** [comment]
Added PR #92 to fix this issue.
